CREATE DATABASE QLDA_PC07859
GO

USE QLDA_PC07859
GO

CREATE TABLE NHANVIEN(
	HONV NVARCHAR(15) NOT NULL,
	TENLOT NVARCHAR(15) NOT NULL,
	TENNV NVARCHAR(15) NOT NULL,
	MANV VARCHAR(9) NOT NULL,
	NGSINH DATE, 
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(3),
	LUONG FLOAT,
	MA_NQL VARCHAR(9),
	PHG INT
) 
GO

CREATE TABLE PHONGBAN(
	TENPHG NVARCHAR(15), 
	MAPHG INT NOT NULL,
	TRPHG VARCHAR(9),
	NG_NHANCHUC DATE,
) 
GO 

CREATE TABLE DIADIEM_PHG(
	MAPHG INT NOT NULL,
	DIADIEM NVARCHAR(15) NOT NULL,
)
GO 

CREATE TABLE THANNHAN(
	MA_NVIEN VARCHAR(9) NOT NULL,
	TENTN NVARCHAR(15) NOT NULL,
	PHAI NVARCHAR(3),
	NGSINH DATE,
	QUANHE NVARCHAR(15),
) 
GO

CREATE TABLE DEAN(
	TENDA NVARCHAR(15),
	MADA INT NOT NULL,
	DDIEM_DA NVARCHAR(15),
	PHONG INT
)
GO

CREATE TABLE CONGVIEC(
	MADA INT NOT NULL,
	STT INT NOT NULL,
	TEN_CONG_VIEC NVARCHAR(50),
)
GO

CREATE TABLE PHANCONG(
	MA_NVIEN VARCHAR(9) NOT NULL,
	MADA INT NOT NULL,
	STT INT NOT NULL,
	THOIGIAN FLOAT,
)
GO

-- PRIMARY KEY
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
ALTER TABLE PHONGBAN ADD CONSTRAINT PK_PHONGBAN PRIMARY KEY(MAPHG)
ALTER TABLE DIADIEM_PHG ADD CONSTRAINT PK_DIADIEM_PHG PRIMARY KEY(MAPHG, DIADIEM)
ALTER TABLE THANNHAN ADD CONSTRAINT PK_THANNHAN PRIMARY KEY(MA_NVIEN, TENTN)
ALTER TABLE DEAN ADD CONSTRAINT PK_DEAN PRIMARY KEY(MADA)
ALTER TABLE CONGVIEC ADD CONSTRAINT PK_CONGVIEC PRIMARY KEY(MADA, STT)
ALTER TABLE PHANCONG ADD CONSTRAINT PK_PHANCONG PRIMARY KEY(MA_NVIEN, MADA, STT)

-- FOREIGN KEY
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_NQL FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PHONGBAN_NHANVIEN FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)
ALTER TABLE DIADIEM_PHG ADD CONSTRAINT FK_DIADIEM_PHONGBAN FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE THANNHAN ADD CONSTRAINT FK_THANNHAN_NHANVIEN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV) 
ALTER TABLE DEAN ADD CONSTRAINT FK_DEAN_PHONGBAN FOREIGN KEY(PHONG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_DEAN FOREIGN KEY(MADA) REFERENCES DEAN(MADA)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_CONGVIEC FOREIGN KEY(MADA, STT) REFERENCES CONGVIEC(MADA, STT)


-- THÊM DỮ LIỆU

INSERT INTO NHANVIEN
VALUES (N'ĐINH', N'BÁ', N'TIÊN', '009', '1960-02-11', N'119 Cồng Quỳnh, Tp HCM', 'Nam', 30000, NULL,  NULL),
(N'NGUYỄN', N'THANH', N'TÙNG', '005', '1962-08-20', N'222 NGUYỄN VĂN CỪ, TP HCM', 'NAM', 40000, NULL, NULL),
(N'BÙI', N'NGỌC', N'HẰNG', '007', '1954-03-11', N'332 NGUYỄN THÁI HỌC, TP HCM', 'NAM', 25000, NULL, NULL),
(N'LÊ', N'QUỲNH', N'NHƯ',  '001', '1967-02-01', N'291 HỒ VĂN HUÊ, TP HCM', N'NỮ', 43000, NULL, NULL),
(N'NGUYỄN', N'MẠNH', N'HÙNG', '004', '1967-03-04', N'95 BÀ RỊA, VŨNG TÀU', 'NAM', 38000, NULL, NULL),
(N'TRẦN', N'THANH', N'TÂM', '003', '1957-05-04',N'34 MAI THỊ LỰ, TP HCM','NAM',25000, NULL, NULL),
(N'TRẦN', N'HỒNG', N'QUANG', '008', '1967-09-01',N'80 LÊ HỒNG PHONG, TP HCM','NAM',25000, NULL, NULL),
(N'PHẠM', N'VĂN', N'VINH', '006', '1965-01-01',N'45 TRƯNG VƯƠNG, HÀ NỘI',N'NỮ',55000, NULL, NULL)
GO

INSERT INTO PHONGBAN
VALUES (N'NGHIÊN CỨU', 5, '005', '1978-05-22'),
(N'ĐIỀU HÀNH', 4, '008', '1985-01-01'),
(N'QUẢN LÝ', 1, '006', '1971-06-19')
GO

UPDATE NHANVIEN
SET MA_NQL = '005', PHG = 5
WHERE MANV = '009'

UPDATE NHANVIEN
SET MA_NQL = '006', PHG = 5
WHERE MANV = '005'

UPDATE NHANVIEN
SET MA_NQL = '001', PHG = 4
WHERE MANV = '007'

UPDATE NHANVIEN
SET MA_NQL = '006', PHG = 4
WHERE MANV = '001'

UPDATE NHANVIEN
SET MA_NQL = '005', PHG = 5
WHERE MANV = '004'

UPDATE NHANVIEN
SET MA_NQL = '005', PHG = 5
WHERE MANV = '003'

UPDATE NHANVIEN
SET MA_NQL = '001', PHG = 4
WHERE MANV = '008'

UPDATE NHANVIEN
SET  PHG = 1
WHERE MANV = '006'

INSERT INTO DIADIEM_PHG
VALUES (1, 'TP HCM'),
	(4, 'HÀ NỘI'),
	(5, 'TAU'),
	(5, 'NHA TRANG'),
	(5, 'TP HCM')


INSERT INTO THANNHAN
VALUES
('005', N'TRINH', N'NỮ', '1976-04-05', N'CON GÁI'),
('005', N'KHANG', N'NAM', '1973-01-25', 'CON TRAI'),
('005', N'PHƯƠNG', N'NỮ', '1948-05-03', N'VỢ CHỒNG'),
('001', N'MINH', N'NAM', '1932-02-29', N'VỢ CHỒNG'),
('009', N'TIẾN', N'NAM', '1978-01-01', N'CON TRAI'),
('009', N'CHÂU', N'NỮ', '1978-12-30', N'CON GÁI'),
('009', N'PHƯƠNG', N'NỮ', '1957-05-05', N'VỢ CHỒNG');


INSERT INTO DEAN
VALUES (N'SẢN PHẨM X', 1, N'VŨNG TÀU', 5)
,(N'SẢN PHẨM Y', 2, 'NHA TRANG', 5)
, (N'SẢN PHẨM Z', 3, 'TP HCM', 5)
,(N'TIN HỌC HÓA', 10,N'HÀ NỘI', 4)
,(N'CÁP QUANG', 20, 'TP HCM', 1)
,(N'ĐÀO TẠO', 30, N'HÀ NỘI', 4)

INSERT INTO CONGVIEC
VALUES (1,1, N'THIẾT KẾ SẢN PHẨM X')
,(1,2, N'THỬ NGHIỆM SẢN PHẨM X')
, (2,1, N'SẢN XUẤT SẢN PHẨM Y')
,(2,2,N'QUẢNG CÁO SẢN PHẨM Y')
,(3,1, N'KHUYẾN MÃI SẢN PHẨM Z')
,(10,1, N'TIN HỌC HÓA PHÒNG NHÂN SỰ')
,(10,2, N'TIN HỌC HÓA PHÒNG KINH DOANH')
,(20,1, N'LẮP ĐẶT CÁP QUANG')
,(30,1,N'ĐÀO TẠO NHÂN VIÊN MARKETING')
,(30,2,N'ĐÀO TẠO CHUYÊN VIÊN THIẾT KẾ')

INSERT INTO PHANCONG
VALUES('009',1,1,32)
,('009',2,2,8)
,('004',3,1,40)
,('003',1,2,20.0)
,('003',2,1,20.0)
,('008', 10,1 , 35)
,('008', 30,2 , 5)
,('001', 30,1 , 20)
,('001', 20,1 , 15)
,('006', 20,1 , 30)
,('005', 3,1 , 10)
,('005', 10,2 , 10)
,('005', 20,1 , 10)
,('007', 30,2 , 30)
,('007', 10,2 , 10)


-- BAI 2

-- Chương trình tính diện tích, chu vi hình chữ nhật khi biết chiều dài và chiều
-- rộng.
DECLARE @dai FLOAT, @rong FLOAT, @cv FLOAT, @dt FLOAT

SET @dai = 10
SET @rong =10
SET @cv = (@dai + @rong) * 2
SET @dt = @dai * @rong

-- SELECT @dientich AS DIENTICHHINHCHUNHAT, @chuvi AS CHUVIHINHCHUNHAT

PRINT N'Chiều dài hình chữ nhật là '+ CONVERT(CHAR(10), @dai)
PRINT N'Chiều rộng hình chữ nhật là '+ CONVERT(CHAR(10), @rong)
PRINT N'Chu vi hình chữ nhật là: ' + CONVERT(CHAR(10), @cv)
PRINT N'Diện tích hình chữ nhật là: '+ CONVERT(CHAR(10), @dt)


-- 1. Cho biêt nhân viên có lương cao nhất
DECLARE @nvlcn TABLE(
	HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15),
	MANV VARCHAR(9),
	NGSINH DATE,
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(3),
	LUONG FLOAT,
	MA_NQL VARCHAR(9),
	PHG INT
)

INSERT INTO @nvlcn
	SELECT NHANVIEN.*
	FROM NHANVIEN
	WHERE NHANVIEN.LUONG = (
		SELECT MAX(LUONG)
		FROM NHANVIEN
	)

SELECT *
FROM @nvlcn


--2. Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương
-- trên mức lương trung bình của phòng "Nghiên cứu”
DECLARE @nvpnclttb TABLE(
	HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15)
)

INSERT INTO @nvpnclttb
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE NHANVIEN.LUONG > (
	SELECT AVG(LUONG)
	FROM NHANVIEN A
	INNER JOIN PHONGBAN B ON A.PHG = B.MAPHG
	WHERE TENPHG LIKE N'%NGHIÊN CỨU%'
	GROUP BY MAPHG, TENPHG
)

SELECT * FROM
@nvpnclttb

--3. Với các phòng ban có mức lương trung bình trên 30,000, liệt kê tên
--phòng ban và số lượng nhân viên của phòng ban đó.
DECLARE @phongban TABLE(
	TENPHONGBAN NVARCHAR(30),
	SLNHANVIEN INT
)
INSERT INTO @phongban
SELECT TENPHG, COUNT(*) AS SOLUONGNHANVIEN
FROM PHONGBAN INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG, NHANVIEN.PHG
HAVING AVG(LUONG) > 30000

SELECT * 
FROM @phongban

--4. Với mỗi phòng ban, cho biết tên phòng ban và số lượng đề án mà
-- phòng ban đó chủ trì
DECLARE @pbvaslda TABLE(
	TENPHONGBAN NVARCHAR(15),
	SLDEAN INT
)

INSERT INTO @pbvaslda
SELECT TENPHG, COUNT(*) AS SOLUONGDEAN
FROM PHONGBAN INNER JOIN DEAN 
ON PHONGBAN.MAPHG = DEAN.PHONG
GROUP BY TENPHG, MAPHG

SELECT *
FROM @pbvaslda

-- BÀI 3. 2Đ Sử dụng biến bảng/biến vô hướng lưu kết quả
-- 1.Hiển thị họ tên đầy đủ nhân viên có người quản lý là Phạm Văn Vinh
USE QLDA_PC07859

DECLARE @nvpvv TABLE(
    HOTENDAYDU NVARCHAR(60)
)

INSERT INTO @nvpvv
	SELECT CONCAT(HONV,' ',TENLOT,' ',TENNV)
	FROM NHANVIEN
	WHERE MA_NQL IN (
		SELECT MANV
		FROM NHANVIEN
		WHERE CONCAT(HONV,' ',TENLOT,' ',TENNV) LIKE N'%PHẠM VĂN VINH%'
	)

SELECT *
FROM @nvpvv

-- 2.Hiển thị thông tin nhân viên không tham gia đề án nào.
DECLARE @nvko TABLE(
HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15),
	MANV VARCHAR(9),
	NGSINH DATE,
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(3),
	LUONG FLOAT,
	MA_NQL VARCHAR(9),
	PHG INT
)

INSERT INTO @nvko
SELECT NHANVIEN.*
FROM NHANVIEN 
LEFT JOIN DEAN ON NHANVIEN.PHG = DEAN.PHONG
WHERE DEAN.PHONG IS NULL

SELECT * 
FROM @nvko


